### ISSUE TITLE
java.lang.NoSuchMethodError: com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init> while calling getNoTx method

### ISSUE THREAD

**Issue by kbsivacse** [orientechnologies/orientdb#8971]
## Expected behavior  
Get non-transactional OrientGraphNoTx object

## Actual behavior  
java.lang.NoSuchMethodError: com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(Lcom/orientechnologies/orient/core/db/OPartitionedDatabasePool;Lcom/tinkerpop/blueprints/impls/orient/OrientConfigurableGraph$Settings;)V

## Steps to reproduce  
OrientGraphFactory factory = new OrientGraphFactory(dbUrl+"/"+dbName,userName, password).setupPool(minConnections, maxConnections);
OrientGraphNoTx noTxGraph = orientGraphFactory.getNoTx();

**Comment by wolf4ood** [comment]
Hi @kbsivacse 

can you share your pom.xml?

Thanks

**Comment by kbsivacse** [comment]
Hi @wolf4ood - I was able to fix this by using the below version of dependencies. But the issue pops up when i upgrade the orientdb-* JAR to 3.0 or greater

spring-data-orientdb-graph - 0.14
spring-boot-orientdb-autoconfigure - 0.13
spring-data-orientdb-object - 0.14
spring-data-orientdb-document - 0.14
orientdb-core - 2.2.37
orientdb-client - 2.2.37
orientdb-object - 2.2.37
orientdb-graphdb - 2.2.37

blueprints-core - 2.6.0
blueprints-orient-graph - 2.4.0

**Comment by tglman** [comment]
Hi,

Version 2.2.x is out of support since a while, closing this.

Regards
