### ISSUE TITLE
Custom function not working after upgrade to 3.0.14

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#8770]
## Actual behavior  
We have a custom function called sort() that allows us to sort the docs taken from an edge. We need this to order the reports associated to an item and get the last one by date. This function looks like this:

```
var list = new java.util.ArrayList();
while (docs.hasNext()) {  
  list.add(docs.next().getRecord());
}

if (order == 'ASC') {
  return list.stream().sorted(function(e1, e2) e2.field(field).compareTo(e1.field(field))).collect(java.util.stream.Collectors.toList());
} else {  
  return list.stream().sorted(function(e1, e2) e1.field(field).compareTo(e2.field(field))).collect(java.util.stream.Collectors.toList());
}
```

Then it is used like this: 
`SELECT last(sort(in('DQReport_DQReportDQMeasure'), 'ReportDate', 'DESC')).DQResult as result FROM DQMeasure`

It was working fine in 2.2.17 but when using this on 3.0.14 I get this error: "docs.hasNext() is not a function in at line number 7". I tried changing the iteration to do this:

```
var list = new java.util.ArrayList();
for (var i = 0; i < docs.size(); i++) {
    list.add(docs[i]);
}

if (order == 'ASC') {
  return list.stream().sorted(function(e1, e2) e2.field(field).compareTo(e1.field(field))).collect(java.util.stream.Collectors.toList());
} else {  
  return list.stream().sorted(function(e1, e2) e1.field(field).compareTo(e2.field(field))).collect(java.util.stream.Collectors.toList());
}
```
In this function, iteration works but I am getting a bunch of nulls into the array list. Then the .field() method fails because of null object. I found it strange as I can do this without issues in the studio:

`select in('DQReport_DQReportDQMeasure')[0].field("Volume") from DQMeasure`

Any suggestion as to how to re-implement this in 3.0.X?. 
Which type of object is returned so I can check on the methods available?

**Comment by ismaelpernas** [comment]
Fixed the custom function by updating the iteration to

```
var iterator = docs.iterator();
while (iterator.hasNext()) {
   var next = iterator.next();list.add(next);
}
```

This matches the object types returned by the in() function.
