### ISSUE TITLE
ER: console command to read and execute a file of SQL commands

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5379]
... like SQLite's ".read FILENAME" command (or MySQL's "source FILENAME" command; etc).

As best I can tell, this is not available in orientdb 2.1.5

EDIT: It's not available in 2.1.7-SNAPSHOT (as of 5 Dec 2015) either.

[EDIT: The suggested workaround for the following "BUILD FAILED" report succeeded.]

p.s.
Building the github version (commit 842ff2ed0b72dabc9bf12590d3f85aeaa582fc61) yields:
BUILD FAILED
orientdb/build.xml:133: The following error occurred while executing this line:
orientdb/build.xml:21: The following error occurred while executing this line:
orientdb/core/build.xml:38: Compile failed; see the compiler error output for details.
...

**Comment by smolinari** [comment]
Try bulding with Maven.

Scott

**Comment by pkoppstein** [comment]
@Scott wrote:
> Try building with Maven

```
$ git log -1
commit 842ff2ed0b72dabc9bf12590d3f85aeaa582fc61
Merge: ca7ecfc 1f10e05
Author: lvca <l.garulli@gmail.com>
Date:   Mon Nov 23 21:01:51 2015 -0600

    Released v2.1.6
$ mvn package
....
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] orientdb/core/src/main/java/com/orientechnologies/common/profiler/OProfilerStub.java:[131,16] error: cannot find symbol
[ERROR]  variable counters of type Map<String,Long>
orientdb/core/src/main/java/com/orientechnologies/common/profiler/OProfilerStub.java:[136,22] error: cannot find symbol
...
[INFO] OrientDB Core ...................................... FAILURE [ 48.688 s]
```

**Comment by smolinari** [comment]
Hmmm...one of the ODB team will need to answer then. 

Scott

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

I think it was already fixed, please try to build 2.1.x branch

Thanks

Luigi

**Comment by luigidellaquila** [comment]
to read a script file from console, just try this from the command line:
```
./console.sh fileName
```

and make sure that the first line of the script is the db connection, eg. ```connect remote:localhost/yourdb ...```

**Comment by pkoppstein** [comment]
@luigidellaquila - Please read the ER.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

what do you mean by ER? 

To get latest build on 2.1 branch try this command sequence:

```
git checkout 2.1.x
git pull
mvn clean install -DskipTests=true
```

Thanks

Luigi

**Comment by pkoppstein** [comment]
"-DskipTests=true" did the trick. Is there something similar for "ant"?   It would be great if "ant clean install" worked reliably.

ER stands for "Enhancement Request".  To be clear, I am requesting that the *existing* console.sh and console.bat command language be extended.  Most REPL interfaces have some kind of "include/read/source" subcommand.  Indeed, it is odd that console.sh does not!

Thank you.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

we are gradually removing duplicated functions from our build process, we are opting for Maven, so Ant will be removed from next release branches.
Got it! I'm flagging it as "enhancement" (this is the label we use for this kind of requests). It should not be hard to implement, if you need it quickly and you want to contribute you can take a look at ```OConsoleDatabaseApp``` and ```OConsoleApplication.run()``` and submit a pull request

Thanks

Luigi

**Comment by pkoppstein** [comment]
@luigidellaquila - The following is tangential to the ER, but you wrote "We are opting for Maven", so I'm wondering whether you've considered Gradle, especially since it treats ant build files as "first class" citizens.  I'm no expert but http://gradle.org/maven_vs_gradle/ is impressive.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

For now we are not considering it, I think in the near future we will stay with Maven

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

For now we are not considering it, I think in the near future we will stay with Maven

Thanks

Luigi

**Comment by rlongre** [comment]
You should not be required to keep usernames and passwords in the script files (the requirement to have "connect remote:localhost/yourdb" as the first line as stated by @luigidellaquila).

For this reason as well, you should be able to open the console, manually connect and authenticate to your desired database, and then issue a command to execute your desired script file against the database you've connected to.

It's terrible to have to commit sql script files to source control with credentials and secrets in them.

**Comment by lvca** [comment]
duplicated

**Comment by robfrank** [comment]
*LOAD SCRIPT* command could solve the probblem?

http://orientdb.com/docs/2.2.x/Console-Command-Load-Script.html

```shell
$ORIENTDB_HOME/bin/console.sh "CONNECT REMOTE:localhost/demo;LOAD SCRIPT /path/to/scripts/data.osql"
```

**Comment by robfrank** [comment]
closing
